### ISSUE TITLE
STA9750 <GITHUB_USERNAME> MiniProject #01

### ISSUE THREAD

**Issue by mussakone** [mussakone/STA9750-2024-FALL#2]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

https://mussakone.github.io/STA9750-2024-FALL/mp01.html

Sorry it's incomplete I was having issues with RStudio memory and time is short

**Comment by michaelweylandt** [comment]
Thanks @mussakone !

Peer Feedback:

- @Gautam-1-R
- @edodia
- @chricannon
- @velasco23

It is now time for the peer feedback round for Mini-Project #01. Please
review @mussakone's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @mussakone, but you are of course
welcome to initiate a discussion.

@mussakone: please engage fully with your peers. They are here to help you!

Submission URL should be: https://mussakone.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by chricannon** [comment]
Your URL works but it appears you did not get through the entirety of the project.

Written communication: 2/10. I can see your title "this is my project" and heading "Here is some text", but there is otherwise no other written text speaking to the code, questions, and findings.

Project Skeleton: 2/10. The instructor provided code was properly included. You answered a few of the prompts, but most of the tasks were not complete.

Formatting & Display: 3/10. The outputs of the code you inputted are properly displaying table outputs, but there are no other tables created or displayed.

Code Quality: 10/10. The code inputted runs properly.

Data Preparation: 10/10. Automatic.

Total: 27/50

**Comment by Edodia** [comment]
Hi @michaelweylandt <https://github.com/michaelweylandt> &  @mussakone
<https://github.com/mussakone>,

Project Skeleton: 6/10. Did not finish however the code was written
correctly and works.
Written Communication: 5/10 Needs more personal discussion of code.However,
there are some comments describing the tasks.
Code Quality: 10/10
Data Prep 10/10
Formatting And Display 7/10: Would look alot better if tables were added,
however it looks readable and clear.

Total  38/50

**Comment by velasco23** [comment]
Hi @mussakone I was able to access your website successfully.

Written Communication - 7/10 although we all know what the project is about adding a little context about the data set and the question/task can add value for future uses.

Project Skeleton - 7/10 would be a 10/10 if it was complete.

Formatting & Display 7/10 - I would recommend to break it up by tasks assigned. 

code quality - 9/10 - variable names made sense. 

 Data Preparation - 10/10

40/50

**Comment by mussakone** [comment]
> Your URL works but it appears you did not get through the entirety of the project.
> 
> Written communication: 2/10. I can see your title "this is my project" and heading "Here is some text", but there is otherwise no other written text speaking to the code, questions, and findings.
> 
> Project Skeleton: 2/10. The instructor provided code was properly included. You answered a few of the prompts, but most of the tasks were not complete.
> 
> Formatting & Display: 3/10. The outputs of the code you inputted are properly displaying table outputs, but there are no other tables created or displayed.
> 
> Code Quality: 10/10. The code inputted runs properly.
> 
> Data Preparation: 10/10. Automatic.
> 
> Total: 27/50
